### ISSUE TITLE
CacheMap shared between all DataLoaders

### ISSUE THREAD

**Issue by rpander93** [overblog/dataloader-bundle#10]
Hi,

Could you please elaborate why the CacheMap is shared between all DataLoaders by default? This gave me all kinds of weird results whereby the promises of different entities were shared. For example, the following query would work if I either included the productType or location field, but not with both.

```
query {
  products {
    id
    productType {
      id
      description    
    }
    location {
      id
      name
    }
  }
}
```
I traced the error by inserting a few lines at https://github.com/overblog/dataloader-php/blob/master/src/DataLoader.php#L66 echo'ing $cacheKey and the $batchLoadFn (as a string) which showed me that the promise of productType would be returned for a location with the same id.

Manually overwriting the service definition as

```
services:
  overblog_dataloader.cache_map:
    public: false
    shared: false
    class: Overblog\DataLoader\CacheMap
```
solved all my problems and gave me the expected results. Is this a bug or am I doing something wrong?
